### ISSUE TITLE
CCM.xsl:58-60: For CCM, cannot add test case for class...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jpeek#148]
The puzzle `66-1f52dc9d` from #66 has to be resolved:

https://github.com/yegor256/jpeek/blob/faea600f44b8a750701047afee520df9bdbeb3a1/src/main/resources/org/jpeek/metrics/CCM.xsl#L58-L60

The puzzle was created by George Aristy on 01-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#148](https://github.com/yegor256/jpeek/issues/148) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#148](https://github.com/yegor256/jpeek/issues/148) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/601404971). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/148#issuecomment-370426822))

@llorllale You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/148#issuecomment-370426822))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#148](https://github.com/yegor256/jpeek/issues/148), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/148#issuecomment-370426822))

@llorllale You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/jpeek/issues/148#issuecomment-370426822))

@llorllale Job `gh:yegor256/jpeek#148` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#148](https://github.com/yegor256/jpeek/issues/148) assigned to @oridan[/z](https://www.0crat.com/u/oridan), here is [why](https://www.0crat.com/footprint/C7JGJ00DP/1371441294); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@oridan[/z](https://www.0crat.com/u/oridan) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by oridan** [comment]
@0crat wait pull request #245 be merged.

**Comment by 0crat** [comment]
> @0crat wait pull request #245 be merged. ([here](https://github.com/yegor256/jpeek/issues/148#issuecomment-391796492))

@oridan The impediment for [#148](https://github.com/yegor256/jpeek/issues/148) was registered successfully by @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0pdd** [comment]
The puzzle `66-1f52dc9d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @oridan[/z](https://www.0crat.com/u/oridan), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#148](https://github.com/yegor256/jpeek/issues/148) is now out of scope

**Comment by elenavolokhova** [comment]
@oridan @uurl Could you please explain who fixed this issue? I can see 2 PRs for it. Issue is assigned to @oridan, but seems to be fixed by @uurl. Do I understand situation correctly?

**Comment by uurl** [comment]
@elenavolokhova correctly, that PR is from long time ago

**Comment by elenavolokhova** [comment]
@0crat quality bad as far as issue was fixed by other person

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by oridan** [comment]
@yegor256 I submited a PR #245 on May 22 with test cases for CCM: here https://github.com/yegor256/jpeek/pull/245/commits/fcece486afcd19b21387b653f4e9dccbb7bf6aa4. Then @uurl got proactive, after all the job was not assigned to him, and also added test case for CCM here https://github.com/uurl/jpeek/commit/bfbd65ac1b6676db65f503ba585e7223846e46e0 On May 27.

I think this resolution, as it is, could cause a bad precedent for Zerocracy. because I'm beeing punished for someone else proactivity.

Please, clarify this, if an proactive colaborator starts submiting pull request over tickets not assigned to him, but to others, those others colaborators will be punished for that, by not getting paid for the time and work spent on the tickets assigned to them, **the performer of the ticket** - the only responsible for the conclusion of the job, see [§7](http://www.zerocracy.com/policy.html#7). If it is so, please, make an policy expliciting that on Zerocracy. If is not this way, please fix this.

**Comment by oridan** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@oridan the rule is simple: you fix the issue and you get paid. If you lose the issue (for any reason), you aren't paid. We don't pay attention to the reason. If this happens, it's your fault. We simply don't want to investigate, since everybody will always have some excuses. We just make rules very strict. If you lose the ticket, it's not yours anymore, you lose everything. In order to prevent a ticket from losing, you should put it on hold: http://www.zerocracy.com/policy.html#9 Make sense?

**Comment by oridan** [comment]
@yegor256 It is not a case of losing an issue. What you said about losing an issue makes perfect sense, because I did prevented it, by putting it on hold for PR #245. 

Then, while the PR was beeing solved, @uurl  comes by and also add a test case for CCM metric. My work was done [here](https://github.com/yegor256/jpeek/commit/fcece486afcd19b21387b653f4e9dccbb7bf6aa4) on May 22, his was done [there](https://github.com/uurl/jpeek/commit/bfbd65ac1b6676db65f503ba585e7223846e46e0) on May 27.

So, could you please answer this: It is OK a collaborator "A", with a ticket **assigned** to him by 0crat, do not get paid because another collaborator "B" submit the same work?

**Comment by oridan** [comment]
@yegor256 ping
