### ISSUE TITLE
Treat primitives and their autoboxed types as one and the same

### ISSUE THREAD

**Issue by llorllale** [yegor256/jpeek#167]
This is basically a copy of #100 

That issue left a puzzle (#166) that was accidentally closed while not resolving the issue. See the comments on #100 for further context.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@llorllale no, this is not how it works :) You opened ticket #100 initially and something was done that moved the project further in the direction that the ticket pointed to. Now you shouldn't care anymore -- everyone was paid in that ticker, the project moved forward, end of story. 

The issue is that, the puzzle that was left to continue implementation was closed by mistake. You also should not care about that, it's the architect's job to make sure the issue tracker is in a consistent state. 

Now, that puzzle was a bit more generic, it asked for implementation of more stylesheets, not specifically the one you wanted (but it does say that we should start with the one mentioned in #100) -- it's more generic because that's what we discussed, we wanted an architecture where more stylesheets could be composed over the skeleton.

Let Yegor decide what to do with that closed puzzle, don't worry about it.

**Comment by amihaiemil** [comment]
@llorllale This being said, I personally think you can close this. But let's see what Yegor says.

**Comment by llorllale** [comment]
@amihaiemil I guess the crux of your argument is:

> it's the architect's job to make sure the issue tracker is in a consistent state

I get that. But I also think we shouldn't stop tracking the original bug/requirement. That's what this ticket is here for.

@yegor256 you decide

**Comment by amihaiemil** [comment]
@llorllale 

>Without this ticket, will the project move towards the goal of "treat primitives and their autoboxed types as one and the same"?

Yes, it should move towards that, I specified in that puzzle that we should start with the XSL that would fix ticket 100. And it is not your job to verify if the assignee of that puzzle implements that XSL, it is the job of the CR and ARCH which will review the Pull Request. If the assinee implements other XSL than the one from 100, they should complain.

**Comment by llorllale** [comment]
@amihaiemil ok, got it

thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/jpeek#167` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#167](https://github.com/yegor256/jpeek/issues/167) was not in scope
