### ISSUE TITLE
Jpeek lacks a technical example

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/jpeek#212]
Could we have some sort of technical documentation, an example of how a metric is implemented with XSLT, start to finish? It doesn't look so complicated, I see people are essentially implementing the formula from the PDF inside XSLT. 

But, how does it work with that skeleton, what is the op/ops elements in a skeleton; how exactly does the skeleton count methods and stuff?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@llorllale If Yegor accepts this then maybe you can do this task, I see you work a lot on Jpeek :)

**Comment by llorllale** [comment]
@amihaiemil I think this project really needs to be fulfilled. :)

**Comment by amihaiemil** [comment]
@llorllale fulfilled, as in closed or what? :D

**Comment by llorllale** [comment]
@amihaiemil also:

> Could we have some sort of technical documentation, an example of how a metric is implemented with XSLT, start to finish? It doesn't look so complicated, I see people are essentially implementing the formula from the PDF inside XSLT.

Exactly, we're implementing the logic in XSLT because the class metadata is reported as an XML. I'm not sure what explanation you think is missing here... The README touches a bit on the subject.

> what is the op/ops elements in a skeleton

The schema for the skeleton has been documented already, see [skeleton.xsd](https://github.com/yegor256/jpeek/blob/master/src/main/resources/org/jpeek/xsd/skeleton.xsd)

> how exactly does the skeleton count methods and stuff?

Not sure what you mean? The skeleton is just a report of everything a class is doing (its method bodies and initializers) and what it has (its attributes and method signatures).

**Comment by amihaiemil** [comment]
@llorllale right, I forgot about that skeleton.xsd -- I'll have a look there. Closing this, then :)

**Comment by llorllale** [comment]
@amihaiemil 
> fulfilled, as in closed or what? 
 
I mean *completed*.
